name: Postman-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Postgres
        run: |
          cd config
          docker-compose -f "docker-compose.yml" up -d --build
      
      - name: Setup Spring Boot App
        run: |
          cd backend/MeetApp
          POSTGRES_USERNAME=postgres POSTGRES_PASSWORD=postgres nohup ./gradlew bootRun

      - name: Install Newman Reporter HTMLExtra
        run: sleep 10 && npm install -g newman-reporter-htmlextra

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "16600135-213d4a64-ab9b-4338-8dd3-c9d0540b1e21"

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down